document:
  type: Allegato alle linee guida
  name: "Allegato 2: Formati di file e riversamento"
  short_name: All.2 Formati file e riversamento
  author: walter-arrighetti
  contributors:
    - Walter Arrighetti
  description: |
    Allegato 2 delle LL.GG. sul documento informatico - Formati di file e Riversamento
  tags:
    - container
    - wrapper
    - busta
    - pacchetto di file
    - tag5
    - QSeal
  origin: https://github.com/test-lg/lg_doc-informatico_A.2/
